import {
  Algeria,
  Argentina,
  Australia,
  Austria,
  Belgium,
  BosniaAndHerzegovina,
  CzechRepublic,
  CongoDR,
  Brasil,
  CaboVerde,
  Canada,
  Colombia,
  CotDIvoire,
  Croatia,
  Curacao,
  Ecuador,
  Egypt,
  England,
  France,
  Germany,
  Ghana,
  Haiti,
  Iran,
  Iraq,
  Japan,
  Jordan,
  Marocco,
  Mexico,
  Netherlands,
  NewZealand,
  Norway,
  Panama,
  Paraguay,
  Portugal,
  Qatar,
  SaudiArabia,
  Scotland,
  Senegal,
  SouthAfrica,
  SouthKorea,
  Spain,
  Sweden,
  Switzerland,
  Tunisia,
  Turkey,
  Uruguay,
  Usa,
  Uzbekistan,
} from "./components/icons/index.jsx";

const FLAGS = {
  Algeria,
  Argentina,
  Australia,
  Austria,
  Belgium,
  BosniaAndHerzegovina,
  CzechRepublic,
  CongoDR,
  Brasil,
  CaboVerde,
  Canada,
  Colombia,
  CotDIvoire,
  Croatia,
  Curacao,
  Ecuador,
  Egypt,
  England,
  France,
  Germany,
  Ghana,
  Haiti,
  Iran,
  Iraq,
  Japan,
  Jordan,
  Marocco,
  Mexico,
  Netherlands,
  NewZealand,
  Norway,
  Panama,
  Paraguay,
  Portugal,
  Qatar,
  SaudiArabia,
  Scotland,
  Senegal,
  SouthAfrica,
  SouthKorea,
  Spain,
  Sweden,
  Switzerland,
  Tunisia,
  Turkey,
  Uruguay,
  Usa,
  Uzbekistan,
};

const FLAG_ALIASES = {
  Brazil: Brasil,
  "Cabo Verde": CaboVerde,
  "Côte d'Ivoire": CotDIvoire,
  "Cote d'Ivoire": CotDIvoire,
  "Ivory Coast": CotDIvoire,
  "Congo DR": CongoDR,
  Morocco: Marocco,
  "New Zealand": NewZealand,
  "Bosnia And Herzegovina": BosniaAndHerzegovina,
  "Bosnia-Herzegovina": BosniaAndHerzegovina,
  "Czech Republic": CzechRepublic,
  "Saudi Arabia": SaudiArabia,
  "Korea Republic": SouthKorea,
  "South Africa": SouthAfrica,
  Turkey: Turkey,
  Türkiye: Turkey,
  Turkiye: Turkey,
  USA: Usa,
  "United States": Usa,
};

const classIcon = "w-8 h-6 rounded-tr-[10px] rounded-bl-[10px]";

export function getFlag(id) {
  const FlagComponent = FLAGS[id] ?? FLAG_ALIASES[id];
  if (!FlagComponent) return null;
  return <FlagComponent className={classIcon} />;
}
