spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
          audiences:
            - ${GOOGLE_OAUTH2_CLIENT_ID:}

  mongodb:
    uri: ${MONGODB_URI:mongodb://root:wc-dreamix@localhost:27017/euro2024?authSource=admin}
    database: ${MONGODB_DATABASE:euro2024}
  # Single Page
  mvc:
    static-path-pattern: /public*
  web:
    resources:
      add-mappings: true

app:
  security:
    allowed-origins:
      - ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
#      We gonna add the Frontend from Tancheto here as well

# OpenAPI
springdoc.packagesToScan: eu.dreamix

server.tomcat.accesslog.enabled: true

football-api:
  url: ${FOOTBALL_API_URL:https://v3.football.api-sports.io}
  api-key: ${FOOTBALL_API_KEY:}
  api-key-header: x-rapidapi-key
  league-id: ${FOOTBALL_API_LEAGUE_ID:1}
  season: ${FOOTBALL_API_SEASON:2024}

#feign
feign:
  client:
    config:
      football-api:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        requestInterceptors:
          - eu.dreamix.wcapi.external.fbapi.ApiKeyInterceptor

scheduler:
  enabled: ${SCHEDULER_ENABLED:false}
  match-retrieval.cron: "${SCHEDULER_MATCH_CRON:0 */30 12-23 * * *}"
  standing-retrieval.cron: "${SCHEDULER_STANDING_CRON:0 0 0 * * *}"
